spring:
  config:
    import: "env.properties"
  data:
    mongodb:
      uri: ${DB_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      database: ${DB_DATABASE}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.ogm.datastore.mongodb.MongoDBDialect
    show-sql: true
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: ${MAILTRAP_USERNAME}
    password: ${MAILTRAP_PASSWORD}
    protocol: smtp

server:
  port: 8081